language: java
script: "./gradlew prepareReleaseNoExe"
before_install: cd MSFragger-GUI
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: mlnpXQrEhogYieL34VglD1Z3wl6O+joIP/zYExFrbpd/QDwLTmBZJ0c9w6xjvLFyXN0guXirPWT8yTjp9QlcB+7z6zyqpr9cV40Bcg2CcrKIinvvGXHD1r8kaKprRr8BdPWDDPJGY8fec7VMMD7MCLxi/V9P4QRI7PF1VYxQ/RdPf3NBxaJQSkKZ3Po135qjVGLms8ZlWCqg0rPvNOPgHAp17Hhf5nIU+qj+7Qv7x/n8xqXj8K3Z+uUlXaaUuO+J5Z1W+uFyh0yjVdLYtRFX8bPLBHxxdUDckhlzSEbARCzw5CpMMOOkkZZzCmW9y8yVAthVXMVR0weO6XD6SN/eQbSkOasGEeY5Q2Jo5q2+iZG0mh9t5kQcvRqEE3s/74K4pXOTb3tSzbudOaldcuuOJlXf62kPd8F+uXLp3+oul+iZR2jImNn6XkpQSxL0nGfiqs6wko73tjdQJSIfMDlD3WhRuuvfATw+w4smn1NhbxvvQq4RdE+dSteRLTulaIqSvxt9VMLXqiqHXM/gyFYzHUvNld7z165V1/32Zlzzih6EtlEzyIeTW32IWMA/Ej0fcWqmZfsunfFs0gFO5T9PBtlNJP+d/aRdpTUm2DcN5n1sqM25tbPEcKdIB7DW4Dbv8KGdz5lD6HgtEVGpd39xgCYxiN/vP8JsZVvhyeZmSgU=
  skip_cleanup: true
  file_glob: true
  file:
  - MSFragger-GUI/build/github-release/*
  - build/github-release/*
  on:
    tags: true
    repo: chhh/FragPipe
notifications:
  slack:
    secure: ADvDWwt1GuDAUCQ8JCYSFN0WL3VFuF35xyGl8UDlvr0obeVFKMGAPw/2Li45nxSdx/9KVcaUS3KM3XtC9wMyVir9F0j0zrCacfIc1W77exDYOTVeZuJEbA6BSS1CWPqGO9HHeipdaX0njCAXmD1N5WCaMlmCxEgfRQxrziVzJhG8Pb0a9K4Z2eMTC7NP4vS1IBWxNyXIIeeCwyB/1pxSoHSo+ICHyOFeU22cGZIducs9+yQruDpYiwCA+EzyrTI6Z2iL+JzhQxJ8XvSJiJVRvJyqOZKOrKOd3BIbNgeIZq7x6dLFbsFIBZe+3W8+M8QkSyzPfuNRRucQ9Wa8ZHBn2q5dZk24jDFq/4iwRroCqOJLQnUlzuOOo4KX6W9Su8JZcKLqIyEzeCnX6tDCc1+w7nYAFdA8Ib048yf8kVZTJwz6sYCAZA9ios99TLlCaJFC8/6IIOjsPXhcyEWtLf2B9rd6XE0vUy8B1E0dRcO2aF+2lIo1T8xWyaXt0lBqk4x9tSJlfWm9rmEiI5vsfd4+F50u1BhhZz37QDeAz+2hznAjIiDWaH847ZA7EYw0FSOe2ZgiHaJdDkEz5r4KEhuREIRqg/7CB6RY6xHzbmVTEHNfuWXMBJJOxyu9iYteZZa7XqpGKhVp/WcbWt1Z/G9L6oEtutJ1jU8hXihVrEcl2jw=
